kind: pipeline
name: default

steps:

  - name: cargo check
    # we need to use this experimental image because the normal rust-musl-builder doesnt
    # allow building as root (and drone doesnt have an easy way to git clone as non-root)
    # https://github.com/emk/rust-musl-builder/issues/96
    image: ekidd/rust-musl-builder:experimental-stable
    user: root
    commands:
      - cargo check --all
    # just to disable this temporarily
    when:
      ref:
        - refs/tags/*

  - name: cargo clippy
    image: ekidd/rust-musl-builder:experimental-stable
    user: root
    commands:
      - cargo clippy
    # just to disable this temporarily
    when:
      ref:
        - refs/tags/*

  - name: check documentation build
    image: ekidd/rust-musl-builder:experimental-stable
    user: root
    commands:
      - mdbook build docs/

  - name: install diesel cli
    image: ekidd/rust-musl-builder:experimental-stable
    user: root
    volumes:
      - name: dieselcli
        path: /dieselcli
    commands:
      - cargo install diesel_cli --no-default-features --features postgres
      - mv /root/.cargo/bin/diesel /dieselcli/diesel
    # just to disable this temporarily
    when:
      ref:
        - refs/tags/*

  - name: cargo test
    image: ekidd/rust-musl-builder:experimental-stable
    user: root
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
      DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1
    volumes:
      - name: dieselcli
        path: /dieselcli
    commands:
      - apt-get -y update
      - apt-get -y install --no-install-recommends espeak postgresql-client
      - /dieselcli/diesel migration run
      - cargo test --workspace --no-fail-fast
    # just to disable this temporarily
    when:
      ref:
        - refs/tags/*

  - name: cargo build
    image: ekidd/rust-musl-builder:experimental-stable
    user: root
    volumes:
      - name: dieselcli
        path: /dieselcli
    commands:
      - cargo build
    # just to disable this temporarily
    when:
      ref:
        - refs/tags/*

  - name: run federation tests
    image: node:15-alpine3.12
    user: root
    commands:
      - ls -la
      - cd api_tests/
      - ls -la
      - bash prepare-drone-federation-test.sh
      - yarn
      - yarn api-test

  - name: create docker tags
    image: ekidd/rust-musl-builder:experimental-stable
    user: root
    commands:
      - echo "$(git describe),latest" > .tags
    when:
      ref:
      - refs/tags/*

  - name: make release build and push to docker hub
    image: plugins/docker
    settings:
      dockerfile: docker/prod/Dockerfile
      #username: kevinbacon
      #password: pa55word
      repo: dessalines/lemmy
    when:
      ref:
      - refs/tags/*

services:
  - name: database
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: lemmy
      POSTGRES_PASSWORD: password
    detach: true

volumes:
  - name: dieselcli
    temp: {}
