kind: pipeline
name: default

steps:
  - name: test
    image: docker/compose:alpine-1.27.4
    commands:
      - docker build . --file docker/prod/Dockerfile --tag dessalines/lemmy:travis
      - docker-compose up -f docker/travis/docker-compose.yml -d
      - sleep 10
      - docker-compose down

