kind: pipeline
name: default

workspace:
  path: /drone/src/docker/travis

steps:
  - name: test
    image: compose:alpine-1.27.4
    commands:
      - docker build ../../ --file ../prod/Dockerfile --tag dessalines/lemmy:travis
      - docker-compose up -d

