kind: pipeline
name: default

steps:
  - name: cargo test
    image: ekidd/rust-musl-builder:1.47.0
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@localhost:5432/lemmy
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1
    commands:
      - ls -la
      - cargo check --all
      - cargo test --workspace --no-fail-fast
      
  - name: run federation tests
    image: docker/compose:alpine-1.27.4
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - cd docker/travis/
      - mkdir -p volumes/pictrs_{alpha,beta,gamma,delta,epsilon}
      - chown -R 991:991 volumes/pictrs_{alpha,beta,gamma,delta,epsilon}
      - docker-compose up -d
      - pushd ../../api_tests
      - echo "Waiting for Lemmy to start..."
      - while [[ "$(curl -s -o /dev/null -w '%{http_code}' 'localhost:8541/api/v1/site')" != "200" ]]; do sleep 1; done
      - while [[ "$(curl -s -o /dev/null -w '%{http_code}' 'localhost:8551/api/v1/site')" != "200" ]]; do sleep 1; done
      - while [[ "$(curl -s -o /dev/null -w '%{http_code}' 'localhost:8561/api/v1/site')" != "200" ]]; do sleep 1; done
      - while [[ "$(curl -s -o /dev/null -w '%{http_code}' 'localhost:8571/api/v1/site')" != "200" ]]; do sleep 1; done
      - while [[ "$(curl -s -o /dev/null -w '%{http_code}' 'localhost:8581/api/v1/site')" != "200" ]]; do sleep 1; done
      - yarn
      - yarn api-test
      - popd
      - docker-compose down

  - name: make release build and push to docker hub
    image: plugins/docker
    settings:
      dockerfile: docker/prod/Dockerfile
      username: kevinbacon
      password: pa55word
      repo: dessalines/lemmy
      tags:
      - latest
    when:
      ref:
      - refs/heads/feature-*
      - refs/tags/*
        
services:
  - name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: lemmy
      POSTGRES_PASSWORD: password
  
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
